apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          ports:
              - containerPort: 8081
